### ISSUE TITLE
no theme on it

### ISSUE THREAD

**Issue by 3gbCyber** [dfirtrack/dfirtrack#130]
Hey! I installed the dfirtrack on my ubuntu 20.4.1 that in my vmware

After I did these steps on this page https://github.com/dfirtrack/dfirtrack/wiki/Installation
I could access to dfirtrack but like what you see in the main page there is no theme! 

![dfirtrack](https://user-images.githubusercontent.com/57197804/129198221-093d0b66-bc07-4578-9a85-885cf48c87ca.png)

Thank you!

**Comment by stuhli** [comment]
Hi,

I guess you forget to turn on debug with `DEBUG = True` in `dfirtrack/settings.yml` needed for minimal setup described at the end of [the description](https://github.com/dfirtrack/dfirtrack/wiki/Installation#minimal-installation).

Did this solve the problem?

**Comment by 3gbCyber** [comment]
> Hi,
> 
> I guess you forget to turn on debug with `DEBUG = True` in `dfirtrack/settings.yml` needed for minimal setup described at the end of [the description](https://github.com/dfirtrack/dfirtrack/wiki/Installation#minimal-installation).
> 
> Did this solve the problem?

It worked, thank you a lot
