### ISSUE TITLE
enable multiple selction of systems to assign tags or tasks of the same kind to them

### ISSUE THREAD

**Issue by stuhli** [dfirtrack/dfirtrack#25]
Original by @TKLau

@stuhli:
Just to be sure:

you either want

1. add task of same kind for multiple systems, or
2. add tag of same kind for multiple systems?

About

1. Could you clarify the difference to the functionality of the Tasks Creator?
2. Check. Should be implemented.

Thx.

@TKLau:
Yes, both would be great. Preferrably from the "systems" view. For example: select multiple systems from the view and then do something like "assign" and then choose "tag" or "task". You are right, this is near to the task creator, but if I have filtered a certain view and then just want to add something to specific systems that would be more intuitive. Task creator is for me something to use if I get a new load of images and want to assign my workflow tasks to them.

**Comment by thomaspatzke** [comment]
In addition, bulk assignment of companies and all other attributes would be useful.

**Comment by stuhli** [comment]
Thx for your input Thomas.

I will have a look at this. I consider integrating the whole into the (new) API.

**Comment by stuhli** [comment]
The original request has now been fulfilled due to many changes in the code and the introduction of workflows with 029eb4c2f39068a2e6ab1a355b5834a3080de159. I therefore close here.

@thomaspatzke
Currently I see no need for this to be done via the GUI. The question is whether fixtures, migration or similar mechanisms make sense for your use case? Please open a new issue if this is still current and describe how you need this.
