### ISSUE TITLE
hide giraf related stuff if not used

### ISSUE THREAD

**Issue by stuhli** [dfirtrack/dfirtrack#35]
All GIRAF API related buttons should not be shown if the API is not in use. Maybe this could be realized by an django app? Or it is possible by `templatetags`?

**Comment by n3x77** [comment]
@stuhli: Thanks for pointing out. I'll take care of this

**Comment by stuhli** [comment]
I already would have done this, but apparently `templatetags` are not evaluated with Jinja2?

My plan was to have something like `GIRAF_BOOL` in `dfirtrack_main.templatetags.dfirtrack_main_tags`. But for incomprehensible reasons `{% if GIRAF_BOOL %}` (e. g. in `systems_list.html`) does not work like I expected it to do.

**Comment by stuhli** [comment]
done with 427ca12a0e1edbc22ff2096cf55455b7f88643e9
